name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # <- Đổi thành recursive để tải đầy đủ theme
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3  # <- Nâng cấp lên v3 bản mới nhất
        with:
          hugo-version: "latest"        # <- Để "latest" để tự động lấy bản mới nhất như máy bạn
          extended: true

      - name: Build website
        run: hugo --minify --buildFuture

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true